---
RuhohSpec: '1.0'
theme : twitter
production_url : 'http://newblue.github.io/YoNg.Blog'

posts:
  permalink: /:categories/:title/
  summary_lines: 20
  latest: 10

editor:

pages:
  permalink: 'pretty'

imgs:
  urlprefix: '{{urls.media}}/'
  localdir: 'media/'

github:
    CNAME:
